# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hipnosis' Stuff
author: Renzo Pigliacampo
email: renzopigliacampo@gmail.com
description: Computers and Graphics Design stuff.
baseurl: ""
url: "https://hipnosis183.github.io"
github_username:  Hipnosis183

# Build settings
theme: jekyll-whiteglass
remote_theme: yous/whiteglass

# Outputting
permalink: /blog/:title/ # set just for blogging.

# Includes
# include:

# Excludes
exclude:
- runlocal
- Gemfile
- Gemfile.lock
